name: Build and Publish Fly.io

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: ./mvnw clean package
    
      - name: Fly.io deploy
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    
