name: 'build'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v3
        with:
          registry: ghcr.io
          username: "phantom08266"
          password: ${{ secrets.CONTAINER_TOKEN }}
          repository: dukki-labs/tech_research
          tags: latest
